package View;

public class BebidaView extends javax.swing.JPanel {

    BEBIDAPREVIEW cantidad = new BEBIDAPREVIEW(null, true);

    /**
     * Creates new form BebidaView
     */
    public BebidaView() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();
        jButton11 = new javax.swing.JButton();
        jButton12 = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 51, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton2.setText("BEBIDA 1");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 110, 100));

        jButton3.setText("BEBIDA2");
        add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 10, 110, 100));

        jButton4.setText("BEBIDA3");
        add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 10, 110, 100));

        jButton6.setText("BEBIDA X");
        add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 120, 110, 100));

        jButton7.setText("BEBIDA X");
        add(jButton7, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 120, 110, 100));

        jButton8.setText("BEBIDA X");
        add(jButton8, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 120, 110, 100));

        jButton10.setText("BEBIDA X");
        add(jButton10, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 230, 110, 100));

        jButton11.setText("BEBIDA X");
        add(jButton11, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 230, 110, 100));

        jButton12.setText("BEBIDA X");
        add(jButton12, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 230, 110, 100));
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        cantidad.setVisible(true);
    }//GEN-LAST:event_jButton2ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    // End of variables declaration//GEN-END:variables
}
